### ISSUE TITLE
BoundHandlers Question

### ISSUE THREAD

**Issue by delatorrena2016** [ryanneph/ChanVese_Levelset_Segmentation#1]
Hi, your BoundHandlers posed me a big difficulty; could you explain the base one? (I don't really know what other use it has other than the constructor), for the clampers and mirrors,  I'd appreciate it a lot if you could explain more that part of the code, and how to run it please.
Very good code though, you're helping me a lot understanding this kind of segmentation, if you could reply fast ('cause I'm really running outta time for a project) it be much appreciated.

**Comment by ryanneph** [comment]
Hi @delatorrena2016,
The base class is meant more as an abstract implementation but I decided to fill it with an implementation that is equivalent to indexing the array without any type of safe boundary handling. This means that if you try to read or write to a set of (i,j) indices that are actually “out-of-bounds” then you _should_ be seeing an exception. It’s not really meant to be used directly in practice. Alternatively I’ve used that base class definition to define two useful safe boundary handling types: with “clamping” and “mirroring”. These are widely used names and my implementation should have the same effect as other computer vision codes that use the same naming. 

For example, using the “clamp” boundary handler, any out-of-bounds array access  will simply return the nearest in-bounds element as if the border of the image was simply extended in each direction an infinite amount. Mirroring instead simulates the situation where the image is tiled next to itself and you begin accessing elements from the next tile. In actuality, only the indices into the original array are modified since expanding or tiling the image would be wasteful and consume more memory than necessary. Another common boundary handler is called “border” or sometimes “constant” and allows you to simply pick which slur should be returned for all out of bounds accesses. Writing out of bounds is always supposed to lead to an exception. 

You should think of the bounds handler classes as wrappers that allow you to to index into the array as you normally would, but behind the scenes it is resolving out of bounds accesses automatically. For example `im[-4, 2]` will no longer act like it does in python, where negative indices are used to get the “last” elements, but will instead act like you are trying to get an element from even further to the left of the array bounds. Depending on which bounds handler class you use to wrap the array and create `im`, these out of bounds accesses will simply return actual values rather than produce an error

I hope my code is instructive. I would really implement the loop in cython to be more efficient but it was a learning exercise and is easier to understand as a pure-python implementation.

**Comment by delatorrena2016** [comment]
I see; just one more thing, how do you run the code? I'ts giving me the exception of supplying the image as argument and other things.
Thanks for your time.

**Comment by ryanneph** [comment]
You can just run it from command line with a single argument as the path to an image file

Best Regards,

Ryan Neph

________________________________
